FROM python:3.11-slim

WORKDIR /ui

RUN pip install --no-cache-dir --upgrade pip

COPY ui_requirements.txt .
RUN pip install --no-cache-dir -r ui_requirements.txt

COPY ui_app.py .

EXPOSE 8501

CMD ["streamlit", "run", "ui_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
